const dot=document.getElementById('curDot'),ring=document.getElementById('curRing');
let mx=0,my=0,rx=0,ry=0;
document.addEventListener('mousemove',e=>{mx=e.clientX;my=e.clientY;dot.style.left=mx+'px';dot.style.top=my+'px';});
(function ar(){rx+=(mx-rx)*.13;ry+=(my-ry)*.13;ring.style.left=rx+'px';ring.style.top=ry+'px';requestAnimationFrame(ar);})();
document.querySelectorAll('a,button,.cs-card,.exp-card,.sk-tile,.cc-card,.pill').forEach(el=>{
  el.addEventListener('mouseenter',()=>{dot.style.width='16px';dot.style.height='16px';dot.style.background='#fb923c';ring.style.width='52px';ring.style.height='52px';ring.style.borderColor='#fb923c';});
  el.addEventListener('mouseleave',()=>{dot.style.width='10px';dot.style.height='10px';dot.style.background='var(--lav2)';ring.style.width='38px';ring.style.height='38px';ring.style.borderColor='var(--lav2)';});
});
window.addEventListener('scroll',()=>document.getElementById('nav').classList.toggle('scrolled',scrollY>60));
const ro=new IntersectionObserver(entries=>{entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add('vis');});},{threshold:.12,rootMargin:'0px 0px -40px 0px'});
document.querySelectorAll('.rl,.rr,.ru').forEach(el=>ro.observe(el));
let pos=0;const CARD=364;
function slide(d){const tr=document.getElementById('carTrack');const max=tr.children.length-3;pos=Math.max(0,Math.min(max,pos+d));tr.style.transform='translateX(-'+(pos*CARD)+'px)';}
const expD={
  jd:{logo:'🔍',bg:'var(--mint3)',co:'Justdial',ro:'Assistant Product Manager · Jun 2024 – Present',items:[
    {m:'10%',s:'Conversion',t:'<strong>AI Bot Integration (Squadstack & Sarvam)</strong> — Led end-to-end integration. Fine-tuned models on agent scripts. Achieved 10% appointment-to-conversion from AI-generated leads.'},
    {m:'70%',s:'QA Saved',t:'<span class="cs-link" onclick="openCS(0)"><strong>LLM Call Audit Engine</strong> — Built LLM-powered QA for ~50,000 calls/month. Turnaround: 5 days → 24 hours. Agent consistency improved by 18%. <br> <strong><i>Click to Read More</i></strong>'},
    {m:'₹4Cr+ ($480K)',s:'Revenue',t:'<span class="cs-link" onclick="openCS(1)"><strong>Lead Reallocation Engine</strong> — Rule-based + performance-weighted logic. Lead utilization up 22%. Generated ₹4 Cr+ ($ 480K) incremental annual revenue. <br> <strong><i>Click to Read More</i></strong>'},
    {m:'4K+',s:'Users',t:'<strong>Genio CRM Scaling</strong> — Scaled agent-side CRM for 4,000+ executives. Intent-driven workflows, scripting logic, zero functional mismatches.'},
    {m:'+7%',s:'Conversions',t:'<strong>Campaign Optimization</strong> — Optimized 100+ lead gen campaigns. Increased average conversion rate by 5–7%.'}
  ]},
  ptm:{logo:'💳',bg:'var(--peach3)',co:'Paytm',ro:'Software Engineer (Front-end) · May – Nov 2023',items:[
    {m:'~10%',s:'Faster',t:'<strong>Paytm Money Stock Mini</strong> — Modularized reusable front-end components. Reduced page load time ~10% for high-traffic financial workflows.'},
    {m:'UX+',s:'Impact',t:'<strong>Interface Improvements</strong> — Identified UX bottlenecks through debugging & QA. Translated financial workflows into scalable API-integrated UI.'}
  ]},
  cap:{logo:'💻',bg:'var(--lav3)',co:'Capgemini',ro:'Senior Analyst · Aug 2021 – May 2023',items:[
    {m:'150+',s:'Issues Fixed',t:'<strong>Inventory Management System</strong> — Resolved 150+ user-reported issues via ServiceNow, root-cause analysis, and workflow improvements.'},
    {m:'~40%',s:'Efficiency',t:'<strong>Operational Efficiency</strong> — Led solution design for recurring issues. Cross-functional coordination increased operational efficiency by ~40%.'}
  ]}
};
function openExp(k){const d=expD[k];const ml=document.getElementById('mLogo');ml.textContent=d.logo;ml.style.background=d.bg;ml.style.fontSize='28px';document.getElementById('mCo').textContent=d.co;document.getElementById('mRo').textContent=d.ro;document.getElementById('mItems').innerHTML=d.items.map(i=>'<div class="mi"><div class="mi-m">'+i.m+'<small>'+i.s+'</small></div><div class="mi-t">'+i.t+'</div></div>').join('');document.getElementById('expMO').classList.add('open');document.body.style.overflow='hidden';}
function closeExpMO(e){if(e.target===document.getElementById('expMO'))closeExpMOD();}
function closeExpMOD(){document.getElementById('expMO').classList.remove('open');document.body.style.overflow='';}
const csD=[
  {em:'🤖',bg:'linear-gradient(135deg,var(--mint3),var(--lav3))',t:'LLM-Powered Call Audit Engine',s:'Justdial · AI/ML · 2024',ch:"Justdial's sales team processed ~50,000 calls/month with fully manual QA — slow, inconsistent, taking 5 days to get feedback to agents.",so:"Designed and shipped an LLM-powered audit engine that transcribes, analyzes, and scores sales calls automatically. Defined scoring rubric, coordinated with ML teams, embedded insights into CRM.",out:[{n:'70%',l:'QA Effort Reduced'},{n:'5d→24h',l:'Feedback Speed'},{n:'+18%',l:'Agent Consistency'},{n:'50K',l:'Calls/Month'}],lrn:"AI output alone is not enough — agents needed structured, actionable feedback, not just scores. The UX of how insights were presented mattered as much as the model itself."},
  {em:'⚙️',bg:'linear-gradient(135deg,var(--peach3),var(--yellow))',t:'Dynamic Lead Reallocation Engine',s:'Justdial · Revenue Engineering · 2024',ch:"Thousands of leads went untouched daily due to static, seniority-based assignment. Revenue leakage was significant and hard to quantify.",so:"Built a hybrid rule-based + performance-weighted system. Leads reassigned based on agent availability, historical conversion rate, lead quality score, and branch capacity in real time.",out:[{n:'+22%',l:'Lead Utilization'},{n:'₹4Cr+ ($ 480K)',l:'Annual Revenue'},{n:'11',l:'Branches Covered'},{n:'Real-time',l:'Reallocation'}],lrn:"Data quality was the real bottleneck — garbage in, garbage out. I spent more time cleaning data inputs than building the allocation logic. Always audit your data pipeline first."},
  {em:'💬',bg:'linear-gradient(135deg,var(--lav3),var(--mint3))',t:'AI Bot Ecosystem Integration',s:'Justdial · AI Integration · 2024',ch:"Sales agents spent too much time on cold outreach. The business wanted AI-powered conversations to handle initial contact and appointment setting at scale.",so:"Led full integration of Squadstack and Sarvam AI bots. Fine-tuned models on real agent scripts, embedded conversations into CRM, built dashboards for analysis.",out:[{n:'10%',l:'Appt. Conversion'},{n:'2',l:'Bots Integrated'},{n:'11',l:'Branches'},{n:'Up',l:'Agent Bandwidth'}],lrn:"Fine-tuning on domain-specific data (agent scripts) was a game-changer. Generic models failed; models trained on how our agents actually spoke performed dramatically better."},
  {em:'📱',bg:'linear-gradient(135deg,var(--yellow),var(--peach3))',t:'Genio CRM Tool Redesign',s:'Justdial · CRM · UX · 2024',ch:"The legacy CRM had zero personalization — every agent saw the same generic lead view regardless of their segment or branch.",so:"Redesigned Genio end-to-end with intent-driven lead displays, dynamic scripting logic based on lead type, and personalized workflow suggestions. Managed full SDLC from JIRA through Figma and production.",out:[{n:'4,000+',l:'Active Users'},{n:'0',l:'Post-Launch Bugs'},{n:'Multi',l:'Use Cases'},{n:'Up',l:'Pitch Quality'}],lrn:"Working with 4,000+ users means you can't afford assumptions. Extensive UAT and feedback sessions with sales HODs were essential to reach zero functional mismatches."},
  {em:'📊',bg:'linear-gradient(135deg,var(--mint3),var(--yellow))',t:'Sales Performance Dashboard',s:'Justdial · Analytics · 2024',ch:"Leadership had no single source of truth for sales performance. Decisions were made on stale weekly reports.",so:"Redesigned web and mobile performance dashboards for sales HODs and senior leadership. Defined the KPI framework, designed the data model, and built real-time metric views.",out:[{n:'100+',l:'Campaigns Tracked'},{n:'+5-7%',l:'Conversion Lift'},{n:'Real-time',l:'Data'},{n:'Web+App',l:'Platform'}],lrn:"The most important design decision was choosing what NOT to show. Leadership doesn't need 50 metrics — they need 5 that actually drive decisions."}
];
function openCS(i){const d=csD[i];const b=document.getElementById('csmBanner');b.textContent=d.em;b.style.background=d.bg;b.style.fontSize='60px';document.getElementById('csmTtl').textContent=d.t;document.getElementById('csmSub').textContent=d.s;document.getElementById('csmBody').innerHTML='<div class="csm-sec"><h4>🎯 The Challenge</h4><p>'+d.ch+'</p></div><div class="csm-sec"><h4>💡 My Approach</h4><p>'+d.so+'</p></div><div class="csm-sec"><h4>📈 Results</h4><div class="csm-res">'+d.out.map(o=>'<div class="csr"><div class="csr-n">'+o.n+'</div><div class="csr-l">'+o.l+'</div></div>').join('')+'</div></div><div class="csm-sec"><h4>🧠 Key Learning</h4><p>'+d.lrn+'</p></div>';document.getElementById('csmoOv').classList.add('open');document.body.style.overflow='hidden';}
function closeCSmO(e){if(e.target===document.getElementById('csmoOv'))closeCSMOD();}
function closeCSMOD(){document.getElementById('csmoOv').classList.remove('open');document.body.style.overflow='';}
document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeExpMOD();closeCSMOD();}});
